spring.datasource.wind.url=jdbc:postgresql://localhost:5432/energy_wind
spring.datasource.wind.username=postgres
spring.datasource.wind.password=postgres
spring.datasource.wind.driver-class-name=org.postgresql.Driver