spring.datasource.solar.url=jdbc:postgresql://localhost:5432/energy_solar
spring.datasource.solar.username=postgres
spring.datasource.solar.password=postgres
spring.datasource.solar.driver-class-name=org.postgresql.Driver