spring.datasource.thermal.url=jdbc:postgresql://localhost:5432/energy_thermal
spring.datasource.thermal.username=postgres
spring.datasource.thermal.password=postgres
spring.datasource.thermal.driver-class-name=org.postgresql.Driver