
server.port=8082
spring.application.name=analytics-service

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false


logging.level.com.energytracker.analytics=DEBUG
