spring.datasource.hydro.url=jdbc:postgresql://localhost:5432/energy_hydro
spring.datasource.hydro.username=postgres
spring.datasource.hydro.password=postgres
spring.datasource.hydro.driver-class-name=org.postgresql.Driver